//
// Created by QWERTY on 6/23/2022.
//

#ifndef NBR_CONFIG_H
#define NBR_CONFIG_H

#define NBR_TAPE_SIZE 0x1000000
#define NBR_TAPE_CENTER (NBR_TAPE_SIZE / 2)

#define NBR_OFFSET_TABLE_SIZE 0x100
#define NBR_OFFSET_TABLE_CENTER (NBR_OFFSET_TABLE_SIZE / 2)

#endif //NBR_CONFIG_H
